In [1]:
import numpy as np

### 多维数组

In [2]:
A = np.array([1, 2, 3, 4])
print(A)

[1 2 3 4]


In [4]:
np.ndim(A) # 查看数组维数

1

In [5]:
A.shape # 查看数组的形状，结果是个元组。这里代表了只有一行，有4个元素

(4,)

In [6]:
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
np.ndim(B)

2

In [9]:
B.shape

(3, 2)

### 数组的乘法

In [11]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [12]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [14]:
C = np.array([[1, 2, 3], [4, 5, 6]])
D = np.array([[1, 2], [3, 4], [5, 6]])
np.dot(C, D)

array([[22, 28],
       [49, 64]])